/*
===============================================================================
Magnitude Analysis
===============================================================================
Purpose:
    - Compare measure values across categories. Tells us about importance of different categories.
SQL Functions Used:
    - Aggregate Functions: SUM(), COUNT(), AVG()
    - GROUP BY, ORDER BY
===============================================================================
*/

-- Find total customers by countries.
SELECT 
    country,
    COUNT(customer_key) AS total_customer
FROM gold.dim_customers
GROUP BY country
ORDER BY total_customer DESC;
-- Find total customers by gender.
SELECT 
    gender,
    COUNT(customer_key) AS total_customer
FROM gold.dim_customers
GROUP BY gender
ORDER BY total_customer DESC;
-- Find total products by categories.
SELECT 
    category,
    COUNT(product_key) AS total_products
FROM gold.dim_products
GROUP BY category
ORDER BY total_products DESC;

-- What is the average cost in each category?
SELECT 
    category,
    AVG(cost) AS avg_cost
FROM gold.dim_products
GROUP BY category
ORDER BY avg_cost DESC;

-- What is total revenue generated by each category?

SELECT 
    p.category,
    SUM(s.sales_amount) AS total_revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_products p
    ON p.product_key = s.product_key
GROUP BY p.category
ORDER BY total_revenue DESC;


-- Find total revenue generated by each each customer.
SELECT 
    c.customer_key,
    c.first_name,
    c.last_name,
    SUM(s.sales_amount) AS total_revenue
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
    ON c.customer_key = s.customer_key
GROUP BY 
    c.customer_key,
    c.first_name,
    c.last_name
ORDER BY total_revenue DESC;

-- What is the distribution of sold items across countries.

SELECT 
    c.country,
    SUM(s.quantity) AS sold_items
FROM gold.fact_sales s
LEFT JOIN gold.dim_customers c
    ON c.customer_key = s.customer_key
GROUP BY c.country
ORDER BY sold_items DESC;
